### ISSUE TITLE
File download issue on Android 13, Redmi Device

### ISSUE THREAD

**Issue by sam829** [nabil6391/flutter_download_manager#21]
E/flutter (26059): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: Cannot create file, path = '/downloads.partial' (OS Error: Read-only file system, errno = 30)
E/flutter (26059): #0      _File.throwIfError (dart:io/file_impl.dart:675:7)
E/flutter (26059): #1      _File.createSync (dart:io/file_impl.dart:306:5)
E/flutter (26059): #2      DioForNative.download (package:dio/src/dio/dio_for_native.dart:93:10)
E/flutter (26059): <asynchronous suspension>
E/flutter (26059): #3      DownloadManager.download (package:flutter_download_manager/src/downloader.dart:94:24)
E/flutter (26059): <asynchronous suspension>
E/flutter (26059):

**Comment by SNNafi** [comment]
This is related to file permission and is not associated with this plugin.
